name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          CONTAINER_IMAGE_BASE: ghcr.io/${{github.repository}}
        run: |
          export IMG_NAME=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]' | tr '-' '_')
          docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} ghcr.io
          docker build -t $CONTAINER_IMAGE_BASE/$IMG_NAME:latest .
          docker push $CONTAINER_IMAGE_BASE/$IMG_NAME:latest
